#! /bin/bash
# updates the bin directory to the most recent encrypt, decrypt, and UI files
cmake .
make
echo "updating decrypt"
cp ./decrypt.app/Contents/MacOS/decrypt ./bin/
echo "decrypt updated"
echo "updating encrypt"
cp ./encrypt.app/Contents/MacOS/encrypt ./bin/
echo "encrypt updated"

if [ -d ../QtCreator/build-433UI-Desktop_Qt_5_12_0_clang_64bit-Debug/433UI.app/Contents/MacOS/ ]; then
   echo "updating debugging too"
   cp ./bin/encrypt ../QtCreator/build-433UI-Desktop_Qt_5_12_0_clang_64bit-Debug/433UI.app/Contents/MacOS/
   cp ./bin/decrypt ../QtCreator/build-433UI-Desktop_Qt_5_12_0_clang_64bit-Debug/433UI.app/Contents/MacOS/
   echo "debugging updated"
fi
echo "updating UI"
cd UI
./updateUI
echo "cleaning up CMake reminants"
cd ..
rm CMakeCache.txt Makefile cmake_install.cmake
rm -Rf CMakeFiles/ decrypt.app/ encrypt.app/
echo "finished cleaning up"
echo "updates complete"
